apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  links: []
  annotations:
    argocd/app-name: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  dependsOn:
    - 'resource:turing'