---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
    spec:
      serviceAccountName: ${{ values.name }}
      containers:
        - name: ${{ values.name }}
          image: ${{ values.dockerImage }}:latest
          ports:
            - containerPort: ${{ values.dockerPort }}
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts: []
          envFrom: []
          livenessProbe: {}
          readinessProbe: {}
      volumes: []