apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []

labels:
  - pairs:
      backstage.io/kubernetes-id: ${{ values.name }}
    includeSelectors: false
    includeTemplates: true
