---
apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
spec:
  ports:
    - port: 80
      targetPort: ${{ values.dockerPort }}
      name: http
  selector:
    app: ${{ values.name }}