apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: default
spec:
  owner: group:default/talbots_court
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: media
spec:
  owner: group:default/talbots_court
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: databasing
spec:
  owner: group:default/talbots_court
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: kubernetes
spec:
  owner: group:default/talbots_court
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: monitoring
spec:
  owner: group:default/talbots_court
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: utilities
spec:
  owner: group:default/talbots_court
