apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: central
spec:
  refreshInterval: 300s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cnpg-cluster-secrets
  target:
    name: central
    template:
      data:
{%- if values.secretUsername %}
        ${{ values.secretUsername }}: '{{ .username }}'
{%- endif %}
{%- if values.secretDbname %}
        ${{ values.secretDbname }}: '{{ .dbname }}'
{%- endif %}
{%- if values.secretHost %}
        ${{ values.secretHost }}: '{{ .host }}'
{%- endif %}
{%- if values.secretPort %}
        ${{ values.secretPort }}: '{{ .port }}'
{%- endif %}
{%- if values.secretUrl %}
        ${{ values.secretUrl }}: '{{ .url }}'
{%- endif %}
{%- if values.secretPassword %}
        ${{ values.secretPassword }}: '{{ .password }}'
{%- endif %}
  dataFrom:
  - extract:
      key: ${{ values.name }}
